microsoft/playwright-pytest

- README.md
- setup.py
- tests/test_playwright.py
Drive by: Use better README test example names.
> fix: use greater than as Playwright requirement

- README.md
- pytest_playwright/pytest_playwright.py
- tests/test_playwright.py
Its breaking, will note it in the release notes.
> chore(typo): fix browse to browser

- .github/workflows/ci.yml
- local-requirements.txt
- pytest_playwright/pytest_playwright.py
- tests/assets/django/settings.py
- tests/assets/django/urls.py
- tests/test_playwright.py
> fix(django): usage with class based tests

- README.md
- pytest_playwright/pytest_playwright.py
Fixes #15
Is this enough for closing #15?
> docs: add examples for custom fixtures

- README.md
- pytest_playwright/pytest_playwright.py
- tests/test_playwright.py
> feat: device emulation

- README.md
Thanks for this great tool.
I hit an error when page was not defined as argument of a test. So I propose this small improvement on the snippet.
> Minor improvement on screenshot hook

- .github/workflows/ci.yml
- pytest_playwright/pytest_playwright.py
- setup.cfg
- setup.py
Fixes https://github.com/microsoft/playwright-test/issues/193#issuecomment-746003307
Fixes https://github.com/microsoft/playwright-pytest/pull/32
Should we make the change backwards compatible? (could try _main and main as a fallback)
> fix: compatible with Playwright 0.170.0

- README.md
- pytest_playwright/pytest_playwright.py
- setup.py
- tests/test_playwright.py
> chore: upgrade to new Playwright with snake case

- README.md
- pytest_playwright/pytest_playwright.py
- tests/test_playwright.py
After that lets maybe release version 1.0?
> chore: replace headful with headed

- README.md
- pytest_playwright/pytest_playwright.py
- tests/test_playwright.py
> test: added test for launch_persistent_context

- pytest_playwright/pytest_playwright.py
- tests/test_playwright.py
> test: re-use context

- .pre-commit-config.yaml
- local-requirements.txt
Fixes https://github.com/microsoft/playwright-pytest/pull/119
> chore: bump dev dependencies

- setup.py
Fixes https://github.com/microsoft/playwright-pytest/issues/125
> chore: have more strict supported dependencies

- local-requirements.txt
- tests/test_playwright.py
Partially resolves https://github.com/microsoft/playwright-python/issues/1442.
> test: add basic pytest-xdist test

- pytest_playwright/pytest_playwright.py
Fixes https://github.com/microsoft/playwright-python/issues/1781
This mirrors the logic from:
https://github.com/microsoft/playwright/blob/6d03211439a5a46b66827e6739d78c4ba7218f50/packages/playwright-test/src/runner/tasks.ts#L145-L150
> fix: best-effort removal of test-results when mounted

- pytest_playwright/pytest_playwright.py
- tests/test_playwright.py
Fixes https://github.com/microsoft/playwright-pytest/issues/153
> fix: respect manual base_url fixture override

- setup.py
The hope here is that this will work perfectly and without issue.
Fixes https://github.com/microsoft/playwright-pytest/issues/159.
> Update to allow the latest `python-slugify`

- tests/test_playwright.py
https://github.com/microsoft/playwright-python/issues/1358
Waiting for the new version to be released, so we can merge this one.
> test: set global expect() timeout

- .github/workflows/ci.yml
- .github/workflows/python-publish.yml
See https://github.com/microsoft/playwright-python/pull/2038
> devops: pin conda + conda-build

- pytest_playwright/pytest_playwright.py
minor, adds trailing comma for black consistency throughout plugin code.
> Add trailing comma for consistent black formatting

- .github/workflows/ci.yml
- .github/workflows/python-publish.yml
Implements changes suggested in https://github.com/microsoft/playwright-pytest/pull/242#issuecomment-2308411945
Test run is made here: https://github.com/microsoft/playwright-pytest/actions/runs/10548603941/job/29222697584
> Fix conda build and publish workflow

- .condarc
- .github/workflows/ci.yml
- .github/workflows/python-publish.yml
- pytest-playwright-asyncio/pytest_playwright_asyncio/pytest_playwright.py
- pytest-playwright/pytest_playwright/pytest_playwright.py
- tests/test_asyncio.py
- tests/test_sync.py
Fixes https://github.com/microsoft/playwright-pytest/issues/197
> feat: allow connecting via connect_options

- .azure-pipelines/publish.yml
Similar to https://github.com/microsoft/playwright-browsers/pull/1524.
> devops: use ESRP PME for publishing

- .azure-pipelines/publish.yml
Similar to https://github.com/microsoft/playwright-python/pull/2733.
> devops: use separate Release job for publishing
