pytest_playwright/pytest_playwright.py
tests/test_playwright.py

Before this change it lead to an AttributeError exception.

fix: report not valid browser names as error

---

README.md

Currently its hard to debug Playwright Pytest tests on bots when they are failing until screencast is not ready. Many users in the Jest world use such a feature for debugging the tests or getting insights why something is not working when they are failing on the bots.
This implementation is opt-in and will create a screenshot when a test is failing, in the future we can add a screencast recording for each test in the folder too.
Blocked by upstream: https://github.com/microsoft/playwright-python/pull/166
I think we could also add a `--breakpoint-on-error` flag e.g. which will start a REPL once a test is failing. Also opt-in. Then the user can interact with the browser via the headful instance or via the REPL.

docs: add guide about debugging Playwright Python

---

README.md

Using the pytest.ini is an advantage if users want to have different command line parameters in their projects and run tests from the IDE. Added a hint on that feature.

docs(readme): add config for pytest.ini

---

.github/workflows/ci.yml
tests/assets/django/settings.py
tests/conftest.py

Configuring **DJANGO_SETTINGS_MODULE** in conftest.py would allow testing without configuring environment variable on CI and locally.
Since the Django tests are not run using Django Test Runner, need to manually configure to use in memory database so that it will not create a test database on the disk. [Django Docs](https://docs.djangoproject.com/en/3.1/topics/testing/overview/#the-test-database)

fix(django): configure DJANGO_SETTINGS_MODULE in conftest.py and use in memory database

---

pytest_playwright/pytest_playwright.py
tests/test_playwright.py

Fix #27 by applying the skip rules in `pytest_runtest_setup` instead of in an `autouse` fixture. Add a test to confirm that tests without browser fixtures are not paramaterized.

Don't paramaterize test functions that don't use browser fixtures

---

setup.py

Not sure if we want to follow the strategy of pinning the versions all the time as we do in playwright-test or using `>=`. Second is probably better now since we follow now SemVer.

chore: bump Playwright to 1.9.0

---

README.md
pytest_playwright/pytest_playwright.py
tests/test_playwright.py

Fixes #55 (verified)
Fixes #54 (verified)

fix: make it compatible with unittest.TestCase

---

.gitignore
pytest_playwright/pytest_playwright.py
setup.py
tests/test_playwright.py

feat: add more testing goodies (screenshot, video, tracing)

---

pytest_playwright/pytest_playwright.py

When running tests in parallel with either pytest-parallel or pytest-xdist, all threads try to delete the output_dir immediately. One thread will have already deleted the files while the other threads are trying to delete files as well which raises an error. This just ignore that error so that tests can still be run

Ignore FileNotFoundError when cleaning up output_dir

---

pytest_playwright/pytest_playwright.py
tests/test_playwright.py

Added a simple check to see if `request.node` is missing the `rep_call` attribute, and assume the test failed if it is missing. This should hopefully fix #89

Added check for if rep_call is missing

---

pytest_playwright/pytest_playwright.py

Hi :wave: 
I believe the `event_loop` fixture is unused (any fixture does not request it - either explicitly or via `request` and doesn't set `autouse=True`), so it can be easily removed.
Thanks for developing `playwright` and this neat pytest plugin!

remove unused event_loop session-scoped fixture

---

meta.yaml

This is how we stumbled on the v prefix issue. 
PIP is fine:
https://github.com/microsoft/playwright-pytest/blob/7fba23af6404b41998de2653b60c1f1b30199052/setup.py#L18

chore(conda): adjust minimal required playwright version

---

pytest_playwright/pytest_playwright.py

Fixes https://github.com/microsoft/playwright-pytest/issues/163

fix: use best-effort artifacts folder removal

---

local-requirements.txt
setup.py

Fixes https://github.com/microsoft/playwright-pytest/issues/202

chore: support Pytest v8

---

pytest_playwright/pytest_playwright.py

Before they were named with a random `name.webm`, now its either `video.webm` or `video-i.webm`.

fix: improve video naming

---

tests/test_playwright.py

Depends on https://github.com/microsoft/playwright-pytest/pull/217.

test: enhance test-artifact assertion utility

---

pytest_playwright/pytest_playwright.py
tests/test_playwright.py

Before this patch manually created contexts were not taken into consideration for tracing, video, and screenshot generation. After this patch tracing and video is fully supported. Screenshots get only taken for pages which are still open, this was already the case before.
The signature of `new_context` needs to be manually getting mirrored, I found no way of doing this like we can in e.g. TypeScript.
Unrelated: Supporting retries might be something we can support in the future, but this is not in scope of this PR.
Fixes https://github.com/microsoft/playwright-pytest/issues/209
Fixes https://github.com/microsoft/playwright-pytest/issues/111
Fixes https://github.com/microsoft/playwright-pytest/issues/99

feat: support artifact collection with multiple contexts

---

pytest_playwright/pytest_playwright.py

Relates https://github.com/microsoft/playwright-python/pull/2410

fix: clean up videos after each test

---

.github/workflows/ci.yml
pytest_playwright/pytest_playwright.py
tests/test_playwright.py

Fixes https://github.com/microsoft/playwright-pytest/issues/222

fix: migrate artifacts_folder to session fixture

---

.azure-pipelines/publish.yml
.github/workflows/python-publish.yml

This is basically a copy of the playwright-python pipeline.
https://github.com/microsoft/playwright-internal/issues/203

devops: migrate publishing to ESRP

---

pytest_playwright/pytest_playwright.py

fix: catch PermissionError when cleaning the tests results with multiple threads (#224)

---

pytest_playwright/pytest_playwright.py

They were exposed by accident - not that users accidentally import them.

chore: hide internal methods

---

local-requirements.txt

Motivation: I had to bump setuptools, otherwise it was not working on my Dev Box with Python 3.12. setuptools is only used during build.

chore: update setuptools to 70.3.0

---

tests/test_playwright.py

Added a `py.typed` file to tell `mypy` (a Python linter) that we are a typed package.
Before we didn't treat https://github.com/microsoft/playwright-pytest/blob/695c3ead82a14874ca10abd2550c1add1f1ae727/pytest_playwright/pytest_playwright.py#L271 as part of our public API - but turns our our customers wants to have a typed `new_context` function which is reasonable.
Is the name `CreateContextCallback` appropriate? We are still under `0.X` releases - so we could rename in theory.
Fixes https://github.com/microsoft/playwright-pytest/issues/244

chore: add py.typed file

---

meta.yaml

Since a few months there is also a `playwright` package on `conda-forge` which is a different conda channel compared to the one we publish. Lets specify explicitly that we want `playwright` from the `microsoft` channel.
Fixes https://github.com/microsoft/playwright-pytest/actions/runs/11251731388/job/31283399122

fix(conda): specify that 'playwright' is from 'microsoft' channel

---

.azure-pipelines/publish.yml
.github/workflows/ci.yml
meta.yaml
setup.cfg
setup.py

Similar to https://github.com/microsoft/playwright-python/commit/f7cfdac7152506c4c41931e453a1ce5dff0474d4 since its EOL and not supported anymore in our dev dependencies.

chore: drop Python 3.8

---

pytest_playwright/pytest_playwright.py
tests/test_playwright.py

This should provide a workaround for https://github.com/microsoft/playwright-pytest/issues/247 and implement #227.
Closes #241
Closes #247
Fixes #227

feat: expose output_path fixture

---

.azure-pipelines/publish.yml

Publish wheels. 
Regressed at #254

devops: publish wheels

---

.github/workflows/ci.yml
local-requirements.txt
setup.cfg
tests/test_asyncio.py

This PR does not include any user-facing changes - its only about our tests. There it updates the `pytest-asyncio` plugin and leverages the new config option which simplifies it.
Relates https://github.com/microsoft/playwright-python/issues/2742.

chore: leverage asyncio_default_test_loop_scope config option

---

tests/test_asyncio.py
tests/test_sync.py

From playwright version 1.52 to version 1.53, the failure output has changed.
From this:
```
============================= test session starts ==============================
platform linux -- Python 3.13.2, pytest-8.4.1, pluggy-1.6.0
rootdir: /tmp/pytest-of-robertofernandez/pytest-22/test_is_able_to_set_expect_timeout_via_conftest0
configfile: pytest.ini
plugins: playwright-0.1.dev144+gdc15f33.d20250703, forked-1.6.0, xdist-2.5.0, base-url-2.1.0, asyncio-1.0.0, cov-3.0.0
asyncio: mode=Mode.STRICT, asyncio_default_fixture_loop_scope=None, asyncio_default_test_loop_scope=function
collected 1 item
test_is_able_to_set_expect_timeout_via_conftest.py F                     [100%]
=================================== FAILURES ===================================
_________________________ …
```

Fix 'test_is_able_to_set_expect_timeout_via_conftest' tests

---

.gitignore
local-requirements.txt
pytest-playwright-asyncio/pytest_playwright_asyncio/pytest_playwright.py
pytest-playwright/pytest_playwright/pytest_playwright.py
tests/conftest.py
tests/test_asyncio.py
tests/test_sync.py

Related to https://github.com/microsoft/playwright-pytest/issues/278 (specifically https://github.com/microsoft/playwright-pytest/issues/278#issuecomment-2941493248).
Per maintainer feedback, this moves the compatibility check between pytest-playwright and pytest-playwright-asyncio from an autouse fixture to the `pytest_addoption` function for earlier detection.
- **Early Detection**: Check now occurs during plugin loading rather than fixture execution
- **Better Error Messages**: Users get clear "plugins are not compatible" errors instead of confusing "option names already added" messages  
- **Type Safety**: Added proper type annotations (`Parser`, `PytestPluginManager`) instead of `Any`
- **Code Quality**: Fixed duplicate imports and ensured all code quality checks pass
The …

feat: move compatibility check from fixture to pytest_addoption hook

---

pytest-playwright-asyncio/pytest_playwright_asyncio/pytest_playwright.py
pytest-playwright/pytest_playwright/pytest_playwright.py

This fixes https://github.com/microsoft/playwright-python/issues/2965 in the `pytest-playwright` project rather than in the `playwright-playwright` project which seems more reasonable, since it keeps it aligned on how we do it in upstream Playwright.
NOTE: The regression was triggered after a change of the screenshot type determination logic in the `playwright-python` project: https://github.com/microsoft/playwright-python/pull/2951
Fixes https://github.com/microsoft/playwright-python/issues/2965
Closes https://github.com/microsoft/playwright-python/pull/2951

fix: use png screenshot type after Playwright v1.55.0 alignment
